services:
  - type: web
    name: enlace-empresarial
    runtime: node
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm run start
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false